openapi: 3.1.0
info:
  title: Densify API
  version: 1.0.0
  description: API to manage user preferences in Densify
paths:
  /user-preferences:
    get:
      summary: Retrieves user preferences
      operationId: getUserPreferences
      responses:
        "200":
          description: User preferences successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    preference_type:
                      type: string
                      description: Type of preference
                    preferences:
                      type: object
                      description: Specific settings for the preference
    put:
      summary: Updates user preferences
      operationId: updateUserPreferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  preference_type:
                    type: string
                    description: Type of preference
                  preferences:
                    type: object
                    description: Specific settings for the preference
      responses:
        "200":
          description: User preferences successfully updated
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "404":
          description: User preferences not found
components:
  schemas:
    UserPreferences:
      type: object
      properties:
        preference_type:
          type: string
          description: Type of preference
        preferences:
          type: object
          description: Specific settings for the preference
