openapi: 3.0.3
info:
  title: Densify Systems -- Analysis Details API
  version: "1.0.0"
  description: |
    Returns instance type analysis details for a system, including:
    - Current instance details
    - Optimal (recommended) instance details
    - Additional target instance options based on the requested **target** set,
      and optional **spend** / **effort** tolerances

    Compatibility priority (highest → lowest):
    1. Insufficient Resources
    2. Technically Incompatible
    3. Outside Spend Tolerance
    4. Outside Effort Tolerance
    5. OK

servers:
  - url: https://{host}
    variables:
      host:
        default: api.example.com
        description: Replace with your Densify API host

tags:
  - name: Systems
    description: Systems analysis endpoints

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AnalysisDetailsEnvelope:
      type: object
      description: Analysis details for the specified entity ID
      required: [current, optimal]
      properties:
        current:
          $ref: '#/components/schemas/InstanceDetails'
        optimal:
          $ref: '#/components/schemas/InstanceDetails'
        targets:
          type: array
          description: Additional instance options based on query inputs (may be omitted for `optimal_instance`)
          items:
            $ref: '#/components/schemas/InstanceDetails'
        message:
          type: string
          description: Informational message returned with the status
        status:
          type: integer
          description: HTTP-like status code for this entity’s analysis
          enum: [200, 400, 401, 404, 500]

    InstanceDetails:
      type: object
      description: Instance characteristics and analysis classification
      properties:
        entityId:
          type: string
          description: Densify unique instance identifier (current section)
        displayName:
          type: string
          description: Cloud provider account/display name (current section)
        resourceId:
          type: string
          description: Cloud provider–assigned identifier (current section)
        azureId:
          type: string
          description: Azure analysis entity resource ID (Azure only; current section)
        resourceGroup:
          type: string
          description: Azure resource group (Azure only; current section)

        instanceType:
          type: string
          description: Instance type (not returned for terminate recommendations in optimal)
        cpuModel:
          type: string
          description: CPU architecture/model (N/A for terminate in optimal)
        numCpus:
          type: integer
          description: Number of vCPUs/CPUs (-1 for terminate in optimal)
        memory:
          type: number
          format: float
          description: Total memory (GB) (-1 for terminate in optimal)
        generation:
          type: integer
          description: Instance generation (-1 for terminate in optimal)
        catalogCost:
          type: number
          format: float
          description: Catalog cost without uptime (-1 for terminate in optimal)

        blendedScore:
          oneOf:
            - type: integer
            - type: number
              format: float
          description: Blended score used to determine compatibility (-1 for terminate)
        compatibility:
          type: string
          description: |
            Compatibility classification. Not present for terminate recommendations.
          enum:
            - Insufficient Resources
            - Technically Incompatible
            - OK
            - Outside Spend Tolerance
            - Outside Effort Tolerance
        recommendationType:
          type: string
          description: Recommendation generated by Densify analysis (optimal section)
        predictedUptime:
          type: number
          format: float
          description: Predicted uptime percentage (current section)
        percentOptimalCost:
          type: number
          format: float
          description: >
            Current/target cost divided by optimal cost; appears in current and targets
        effortEstimate:
          type: string
          description: Effort required to implement the change (optimal/targets)

  parameters:
    PathId:
      name: id
      in: path
      required: true
      description: Unique entity ID of the instance to analyze
      schema:
        type: string
    Target:
      name: target
      in: query
      required: true
      description: |
        Target set to return.
        - `all_instances`: include all targets
        - `compatible_instances`: only targets with compatibility `OK`
        - `incompatible_instances`: only targets with compatibility != `OK`
        - `optimal_instance`: only the optimal instance (no `targets` array)
        - `<instanceType>`: a specific instance type name (e.g., `m6i.large`)
      schema:
        type: string
    SpendTolerance:
      name: spendTolerance
      in: query
      required: false
      description: |
        Decimal *multiplier* threshold above which a target is considered outside spend tolerance.
        Example: `1.2` ⇒ allow up to 20% higher cost than current.
        Affects the `compatibility` value but does not limit the count returned under `targets`.
      schema:
        type: number
        format: float
    EffortTolerance:
      name: effortTolerance
      in: query
      required: false
      description: |
        Maximum acceptable implementation effort for a target to be considered compatible.
        Values (in increasing permissiveness): `very_low`, `low`, `moderate`, `high`.
        Affects the `compatibility` value but does not limit the count returned under `targets`.
      schema:
        type: string
        enum: [very_low, low, moderate, high]

security:
  - bearerAuth: []

paths:
  /systems/{id}/analysis-details:
    get:
      tags: [Systems]
      operationId: getSystemAnalysisDetails
      summary: Get a system's instance type details
      description: |
        Provides the current instance details, the optimal (recommended) instance,
        and an optional list of additional targets based on `target`, `spendTolerance`,
        and `effortTolerance` inputs.
      parameters:
        - $ref: '#/components/parameters/PathId'
        - $ref: '#/components/parameters/Target'
        - $ref: '#/components/parameters/SpendTolerance'
        - $ref: '#/components/parameters/EffortTolerance'
      responses:
        '200':
          description: Analysis details for the requested system
          content:
            application/json:
              schema:
                type: array
                description: A list of result envelopes (one per supplied entity ID)
                items:
                  $ref: '#/components/schemas/AnalysisDetailsEnvelope'
              examples:
                compatibleWithinSpend:
                  summary: Compatible targets within 30% spend tolerance (Azure)
                  value:
                    - current:
                        entityId: 076e70cf-cff2-3cc6-8a4c-54200241de7c
                        displayName: testsystem
                        resourceId: 9a0546d2-f4e1-46f0-bc09-a7422a6b72927
                        azureId: /subscriptions/cc377154-9605-4cb0-8b41-1b39e1c/resourcegroups/testsystem/providers/microsoft.compute/virtualmachines/testsystem
                        resourceGroup: testsystem
                        instanceType: Standard_DS1_v2
                        blendedScore: 90
                        compatibility: Outside Spend Tolerance
                        cpuModel: Intel Xeon E5-2673 v3
                        numCpus: 1
                        memory: 3.5
                        generation: 2
                        catalogCost: 53.29
                        predictedUptime: 84.51
                        percentOptimalCost: 7.0210805
                      optimal:
                        instanceType: Standard_B1s
                        blendedScore: 99
                        compatibility: OK
                        recommendationType: Downsize - Optimal Family
                        cpuModel: Intel Haswell E5-2673 v3
                        numCpus: 1
                        memory: 1.0
                        generation: 4
                        catalogCost: 7.59
                        effortEstimate: Low
                      targets:
                        - instanceType: Standard_B1s
                          cpuModel: Intel Haswell E5-2673 v3
                          numCpus: 1
                          memory: 1.0
                          generation: 4
                          catalogCost: 7.59
                          blendedScore: 99
                          compatibility: OK
                          percentOptimalCost: 1.0
                          effortEstimate: Low
                allWithSpendAndEffort:
                  summary: All instances with spend=1.5 and effort=low (AWS)
                  value:
                    - current:
                        entityId: 123451231231-123-123-123
                        displayName: testsystem
                        resourceId: 456789-123-5657
                        instanceType: c5.2xlarge
                        blendedScore: 95
                        compatibility: OK
                        cpuModel: Intel Xeon
                        numCpus: 8
                        memory: 16.0625
                        generation: 7
                        catalogCost: 11.43
                      optimal:
                        instanceType: r5.xlarge
                        blendedScore: 99
                        catalogCost: 12.00
                        compatibility: OK
                        recommendationType: Downsize - Optimal Family
                        effortEstimate: Very Low
                      targets:
                        - instanceType: m5.8xlarge
                          blendedScore: 87
                          catalogCost: 80.00
                          compatibility: Outside Spend Tolerance
                          effortEstimate: Low
                        - instanceType: r5.xlarge
                          blendedScore: 99
                          catalogCost: 12.00
                          compatibility: OK
                          effortEstimate: Very Low
                        - instanceType: r5.8xlarge
                          blendedScore: 88
                          catalogCost: 96.00
                          compatibility: Outside Spend Tolerance
                          effortEstimate: Very Low
                        - instanceType: m6g.2xlarge
                          blendedScore: 77
                          catalogCost: 14.00
                          compatibility: Outside Effort Tolerance
                          effortEstimate: Moderate
        '201':
          description: |
            The API may also return 200 with a non-error `status` field indicating:
            - Entity Not Analyzed
            - Instance Type Analysis is Disabled
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AnalysisDetailsEnvelope'
        '400':
          description: Invalid parameter(s)
        '401':
          description: Unauthorized
        '404':
          description: Entity not found
        '500':
          description: Internal server error
