openapi: 3.1.0
info:
  title: Densify – GCP Analysis Delete API
  version: "1.0.0"
  description: >
    DELETE `/analysis/cloud/gcp/{analysisId}` deletes the audit and its scheduler entries.
    Removes single-day and 60-day historical audits if present. Fails for many-to-one
    (aggregate) connections created via the Cloud Connection Wizard; those must be
    deleted via the Wizard. While delete is in progress, other ops on the same analysisId
    return 400. Collected data and the analysis structure remain available for reporting.
servers:
  - url: https://{host}
    variables:
      host:
        default: api.example.com
tags:
  - name: GCP Analysis
paths:
  /analysis/cloud/gcp/{analysisId}:
    delete:
      tags: [GCP Analysis]
      operationId: deleteGcpAnalysisAudit
      summary: Delete GCP data-collection audit for an analysis
      description: |
        Deletes the audit and associated scheduler entries for the specified analysis.
        Status may be sent to an optional webhook on completion.
      parameters:
        - name: analysisId
          in: path
          required: true
          description: The unique referenced ID of the GCP analysis.
          schema:
            type: string
      requestBody:
        required: false
        description: Optional webhook to receive completion status.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteWebhook'
            examples:
              withWebhook:
                value:
                  webHook:
                    uri: "http://mywebhookserver/webhook/results"
                    authType: "basic"
                    authValue: "user:pass"
      responses:
        '200':
          description: OK -- delete accepted/completed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusMessage'
              examples:
                ok:
                  value: { message: "OK", status: 200 }
        '400':
          description: Bad Request (e.g., other ops attempted during delete).
        '401':
          description: Authentication failed.
        '404':
          description: Analysis not found.
        '405':
          description: Method not allowed.
        '500':
          description: Server error (e.g., audit in progress or aggregate connection).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusMessage'
              examples:
                inProgress:
                  value:
                    message: "Connection has an audit in progress. It cannot be deleted at this time."
                    status: 500
                aggregate:
                  value:
                    message: "Account dfc04848-3848-44c0-b85a-02311951de36 was created via UI and subscriptions [cc377154-9605-4cb0-8b41-1b39e1c4ac0f,3d4ba999-cbd8-40b8-9998-574be6824a97] are incompatible with API use; please delete via UI"
                    status: 500

components:
  schemas:
    DeleteWebhook:
      type: object
      additionalProperties: false
      properties:
        webHook:
          type: object
          additionalProperties: false
          properties:
            uri:
              type: string
              format: uri
            authType:
              type: string
              description: Authentication scheme ("basic", "bearer", etc.).
            authValue:
              type: string
              description: Credential value.
          required: [uri]
    StatusMessage:
      type: object
      additionalProperties: false
      properties:
        message: { type: string }
        status:
          type: integer
          description: One of 200, 400, 401, 404, 405, 500.
      required: [message, status]
