openapi: 3.1.0
info:
  title: Densify – Kubernetes Container Systems API
  version: "1.0.0"
  description: |
    GET `/analysis/containers/kubernetes/{analysisId}/systems` lists all container
    systems included in a Kubernetes analysis (may be ≥ recommendation count).
servers:
  - url: https://{host}
    variables:
      host:
        default: api.example.com
tags:
  - name: Kubernetes Analysis
paths:
  /analysis/containers/kubernetes/{analysisId}/systems:
    get:
      tags: [Kubernetes Analysis]
      operationId: listKubernetesContainerSystems
      summary: List systems included in a Kubernetes container analysis
      parameters:
        - name: analysisId
          in: path
          required: true
          description: Unique ID of the Kubernetes container analysis.
          schema: { type: string }
      responses:
        '200':
          description: Array of container systems in the analysis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/K8sContainerSystem'
              examples:
                sample:
                  value:
                    - hostName: "d3cf25f4-01b1-4c0b-66a8-86bd1ea771d3"
                      displayName: "kube-abcserver-kube-ctrl.densify.com__kube-abcserver"
                      entityId: "06770825-988a-4aa4-b047-41bda995a69e"
                      href: "/systems/06770825-988a-4aa4-b047-41bda995a69e"
        '401':
          description: Authentication failed.
        '404':
          description: Analysis not found.
        '500':
          description: Server error.

components:
  schemas:
    K8sContainerSystem:
      type: object
      description: Container system included in the Kubernetes analysis.
      properties:
        hostName:
          type: string
          description: Densify internal reference ensuring uniqueness across clusters.
        displayName:
          type: string
          description: Combination of pod and container name.
        entityId:
          type: string
          description: Densify entity ID of the container system.
        href:
          type: string
          description: Link to the `/systems/{entityId}` resource.
      required: [hostName, displayName, entityId, href]
